version: "3.8"

services:
  db:
    image: postgres:14
    container_name: django_db
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_app
    # Используем entrypoint.sh, который выполняет ожидание БД, миграции, загрузку фикстур и создание суперпользователя
    command: sh -c "/app/entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Переопределяем PG_HOST, чтобы Django подключался к контейнеру db
      PG_HOST: db
    depends_on:
      - db

volumes:
  pgdata:
