# Generated by Django 5.1.4 on 2025-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение'),
        ),
    ]
