# Generated by Django 5.1.4 on 2025-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
